import type { Palette, SpriteFrame } from "./pixel";

export const PALETTE: Palette = {
  ".": "rgba(0,0,0,0)",
  K: "#1a1a1a",
  W: "#ffffff",
  S: "#fff5e6",
  P: "#ffc4c4",
  R: "#e84a4a",
  Y: "#ffd860",
  G: "#5fbf6f",
  B: "#3d7be8",
  L: "#a78bfa",
  O: "#f59e3b",
  C: "#9ca3af",
  D: "#4b5563",
  N: "#1f2937",
  E: "#fde2e4",
  Q: "#f8c8dc",
  T: "#d4a373",
  U: "#a87c4f",
  X: "#0a0a0a",
  M: "#7e3a93",
  H: "#0d61a9",
  J: "#fff1c1",
};

export const GROOM_RABBIT_IDLE: SpriteFrame = [
  "....KK....KK....",
  "...KEEK..KEEK...",
  "...KEEK..KEEK...",
  "...KEEK..KEEK...",
  "....KSSKKSSK....",
  "...KSSSSSSSSK...",
  "..KSXSSSSSXSSK..",
  "..KSSSSSSSSSSK..",
  "..KSSPPSSPPSSK..",
  "...KSSSSSSSSK...",
  "....KKWWWWKK....",
  "...KWWRRRRWWK...",
  "...KWWWRWWWWK...",
  "...KKWWWWWWKK...",
  "....KK....KK....",
  ".....K....K.....",
];

export const GROOM_RABBIT_RUN: SpriteFrame = [
  "....KK....KK....",
  "...KEEK..KEEK...",
  "...KEEK..KEEK...",
  "...KEEK..KEEK...",
  "....KSSKKSSK....",
  "...KSSSSSSSSK...",
  "..KSXSSSSSXSSK..",
  "..KSSSSSSSSSSK..",
  "..KSSPPSSPPSSK..",
  "...KSSSSSSSSK...",
  "....KKWWWWKK....",
  "...KWWRRRRWWK...",
  "..KWWWWRWWWWWK..",
  "..KKWWWWWWWWKK..",
  "...KK......KK...",
  "..KK........KK..",
];

export const BRIDE_IDLE: SpriteFrame = [
  ".....WWWWW......",
  "....WWWWWWW.....",
  "...WWKKKKKWW....",
  "...WKEEEEKWW....",
  "...WKEXEXEKW....",
  "...WKEEEEEKW....",
  "....KKPPPKK.....",
  "...WSSSSSSSW....",
  "..WWWWWSSWWWWW..",
  "..WWWWWWWWWWWW..",
  "..WWQQWWWWQQWW..",
  "..WWWWWWWWWWWW..",
  "..WWWWWWWWWWWW..",
  "...WWWWWWWWWW...",
  "....KK....KK....",
  ".....K....K.....",
];

export const FRIEND_BRIDESMAID: SpriteFrame = [
  "......CCCC......",
  ".....CCDDCC.....",
  "....CCDDDDCC....",
  "...CDEEEEEEDC...",
  "...CDEXEEXEDC...",
  "...CDEEEEEEDC...",
  "....CDPPPPDC....",
  "....CSSSSSSC....",
  "...CLLLLLLLLC...",
  "...CLLLLLLLLC...",
  "...CLPPLLPPLC...",
  "...CLLLLLLLLC...",
  "...CLLLLLLLLC...",
  "....CLLLLLLC....",
  ".....KK..KK.....",
  "......K..K......",
];

export const ELDER_PROFESSOR: SpriteFrame = [
  ".....CCCCCC.....",
  "....CCCCCCCC....",
  "...CCWWWWWWCC...",
  "...CWEEEEEEWC...",
  "...WKKEEEEKKW...",
  "...WEKEEEEKEW...",
  "....WEEPPEEW....",
  "....WWWWWWWW....",
  "...WWWWWWWWWW...",
  "..WWWWWWWWWWWW..",
  "..WJJJJJJJJJJW..",
  "..WJWWWWWWWWJW..",
  "..WJJJJJJJJJJW..",
  "...WWWWWWWWW....",
  "....KK....KK....",
  ".....K....K.....",
];

export const KID_NPC: SpriteFrame = [
  "................",
  ".................",
  "......OOOO......",
  ".....OEEEEO.....",
  ".....OXEEXO.....",
  ".....OEEEEO.....",
  "......OPPPO.....",
  ".....RRRRRR.....",
  ".....RRYYRR.....",
  ".....RRRRRR.....",
  ".....RRRRRR.....",
  ".....RR..RR.....",
  ".....KK..KK.....",
  "................",
  "................",
  "................",
];

export const RING_ITEM: SpriteFrame = [
  "................",
  "................",
  "......YYYY......",
  ".....YWWYYY.....",
  "....YYJJYYYY....",
  "....YJJJJYYY....",
  "....YYJJYYYY....",
  ".....YYYYYY.....",
  "......YYYY......",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
];

export const HEART_ITEM: SpriteFrame = [
  "................",
  ".....RR..RR.....",
  "....RRRRRRR.....",
  "...RRRWWRRRRR...",
  "...RRRRRRRRRR...",
  "....RRRRRRRR....",
  ".....RRRRRR.....",
  "......RRRR......",
  ".......RR.......",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
];

export const CHAMPAGNE_ITEM: SpriteFrame = [
  "......YYYY......",
  ".....YJJJJY.....",
  ".....YJWWJY.....",
  ".....YJJJJY.....",
  "......YYYY......",
  ".......YY.......",
  "......YYYY......",
  ".....JJYYJJ.....",
  "....JJJJJJJJ....",
  "....JJJJJJJJ....",
  "....JJWWWWJJ....",
  ".....JJJJJJ.....",
  "......JJJJ......",
  ".......JJ.......",
  "......JJJJ......",
  ".....JJJJJJ.....",
];

export const ENVELOPE_HAZARD: SpriteFrame = [
  "................",
  "................",
  "..WWWWWWWWWWWW..",
  "..WCCCCCCCCCCW..",
  "..WCWWCCCCWWCW..",
  "..WCWCWCWCWCWW..",
  "..WCCCWWWWCCCW..",
  "..WCCCCWWCCCCW..",
  "..WCCCCCCCCCCW..",
  "..WWWWWWWWWWWW..",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
];

export const CAKE_HAZARD: SpriteFrame = [
  ".......RR.......",
  "......RRRR......",
  "......WWWW......",
  ".....WWWWWW.....",
  "....WWPPPPWW....",
  "....WWWWWWWW....",
  "....WWWWWWWW....",
  "...WWWPPPPWWW...",
  "...WWWWWWWWWW...",
  "...WWWWWWWWWW...",
  "..WWWPPPPPPWWW..",
  "..WWWWWWWWWWWW..",
  "..WWWWWWWWWWWW..",
  "..WWPPPPPPPPWW..",
  "..WWWWWWWWWWWW..",
  "..KKKKKKKKKKKK..",
];

export const CHAPEL_BUILDING: SpriteFrame = [
  "................",
  "........K.......",
  ".......KKK......",
  "......KKKKK.....",
  ".....WWKKWWW....",
  "....WWWWWWWWW...",
  "...WWWWWWWWWWW..",
  "..WWWWWWWWWWWWW.",
  "..WWWHHWWWHHWWW.",
  "..WWWHHWWWHHWWW.",
  "..WWWWWWWWWWWWW.",
  "..WWWWWKKWWWWWW.",
  "..WWWWWKKWWWWWW.",
  "..WWWWWKKWWWWWW.",
  "..KKKKKKKKKKKKK.",
  "..KKKKKKKKKKKKK.",
];

export const TILE_GRASS: SpriteFrame = [
  "GGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGG",
  "GGGYGGGGGGGYGGGG",
  "GGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGG",
  "GGGGGGGGGYGGGGGG",
  "GGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGG",
  "GGYGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGYGG",
  "GGGGGGGGGGGGGGGG",
  "GGGGGYGGGGGGGGGG",
  "GGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGG",
  "GGGGGGGGGGGGGGGG",
];

export const TILE_PATH: SpriteFrame = [
  "TTTTTTTTTTTTTTTT",
  "TUUTUTTTTUUTTUTT",
  "TTTUTTTUTTUTTTTU",
  "TUTTTTTTTTUTTTTU",
  "TTTUTUUTTTTUTTTT",
  "TTTTUTTTTTTTUUTU",
  "TUTTUTTUTTTTUTTU",
  "TUUTTTTTTUUTTTTT",
  "TTTUTUTTTUTUTTTT",
  "UTUTTTUTTTTTUUTU",
  "TTTUUUTTTUTTUTTU",
  "TUTTUTUTUTTTTTUT",
  "TTUTUTTTTTUTUTUT",
  "TUTTTTTUTTTTUTTU",
  "TTTUUTTTTUUTUTTT",
  "TTTTTTUUTTTUTTTU",
];

export const TILE_HOUSE_ROOF: SpriteFrame = [
  "RRRRRRRRRRRRRRRR",
  "RDDRRRRRRRRRRRRR",
  "RRDDDRRRRRRRRRRR",
  "RRRRDDDRRRRRRRRR",
  "RRRRRRDDDRRRRRRR",
  "RRRRRRRRDDDRRRRR",
  "RRRRRRRRRRDDDRRR",
  "RRRRRRRRRRRRDDDR",
  "DDDDDDDDDDDDDDDD",
  "WWWWWWWWWWWWWWWW",
  "WWHHWWWWWWWHHWWW",
  "WWHHWWWWWWWHHWWW",
  "WWWWWWWWWWWWWWWW",
  "WWWWWWKKWWWWWWWW",
  "WWWWWWKKWWWWWWWW",
  "KKKKKKKKKKKKKKKK",
];

export const TILE_TREE: SpriteFrame = [
  "....GGGGGGGG....",
  "...GGGGGGGGGG...",
  "..GGGGGGGGGGGG..",
  "..GGYGGGGGGGGG..",
  "..GGGGGGGGYGGG..",
  "..GGGGGGGGGGGG..",
  "..GGGYGGGGGGGG..",
  "...GGGGGGGGGG...",
  "....GGGGGGGG....",
  ".......TT.......",
  ".......TT.......",
  ".......TT.......",
  ".......TT.......",
  "......TUTU......",
  ".....TUTUUT.....",
  "....TUUTUUTU....",
];
